[program:sismo-reverb]
command=/usr/bin/php /home/USUARIO/domains/DOMINIO/public_html/artisan reverb:start --host=0.0.0.0 --port=8080
directory=/home/USUARIO/domains/DOMINIO/public_html
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/home/USUARIO/domains/DOMINIO/public_html/storage/logs/reverb.log
redirect_stderr=true

[program:sismo-emsc]
command=/usr/bin/php /home/USUARIO/domains/DOMINIO/public_html/artisan earthquakes:listen-emsc
directory=/home/USUARIO/domains/DOMINIO/public_html
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/home/USUARIO/domains/DOMINIO/public_html/storage/logs/emsc.log
redirect_stderr=true

[program:sismo-queue]
command=/usr/bin/php /home/USUARIO/domains/DOMINIO/public_html/artisan queue:work --sleep=1 --tries=3 --timeout=60
directory=/home/USUARIO/domains/DOMINIO/public_html
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=1
stdout_logfile=/home/USUARIO/domains/DOMINIO/public_html/storage/logs/queue.log
redirect_stderr=true
